### ISSUE TITLE
Github User name 

### ISSUE THREAD

**Issue by Aiijay** [coinratecap/Design#1]
Drop all Github user name below

**Comment by Aiijay** [comment]
Slack Name: Noor Ahmd  Github: @NoorAhmd

 Slack Name: Wisdom Ekpot Github: @Wisdom132

Slack Name: NotUsualTechDude Github: @Sam-Devs

**Comment by dhakal0kushal** [comment]
Slack Name: Hussu; Github: dhakal0kushal

**Comment by Aiijay** [comment]
Slack name: Sangamesh - Backend Dev Github username: @sangamkotalwar

Slack name: Maybank Gupta Github username : @bong-o-hari

Slack Name: Hussu; Github: @dhakal0kushal

**Comment by Aiijay** [comment]
Slack name: Justine Peterson Github Username: @justinepeterson

Slack name: Melody Daniel Github Username: @melodyogonna

Slack name: Devansh  Gajjah Github Username: @devanshgajjar

Slackname: Raghav Dadhwal  Github Username: @RaghavDadhwal007

**Comment by melodyogonna** [comment]
Slack username: Melody Daniel, GitHub: melodyogonna
